name             'railsbox'
maintainer       'AkitaOnRails'
maintainer_email 'boss@akitaonrails.com'
license          'All rights reserved'
description      'Installs/Configures .'
long_description 'Installs/Configures .'
version          '0.1.0'

depends 'chef-locale'
depends 'htop'
depends 'git'
depends 'curl'
depends 'zlib'
#depends 'java'
#depends 'mysql'
depends 'postgresql'
depends 'redisio'
depends 'imagemagick'
depends 'heroku'
#depends 'mongodb'
#depends 'elasticsearch'
depends 'nodejs'
depends 'rvm'
depends 'user'
depends 'memcached'
depends 'ntp'
#depends 'zsh'
#depends 'lxmx_oh_my_zsh'
